### ISSUE TITLE
make validate() also accept bound properties

### ISSUE THREAD

**Issue by fmobus** [valiktor/valiktor#17] opened 2019-05-18 02:10 UTC
## Is your feature request related to a problem? Please describe.
For brevity, I would like to be able to avoid writing the class name over over and over again inside my validation block, i.e.:

        validate(this) {
            validate(OrganizationAdminsitrator::name).isNotNull().isNotBlank()
            validate(OrganizationAdminsitrator::taxId).isNotNull().isNotBlank()
            validate(OrganizationAdminsitrator::phone).isNotNull().isNotBlank()
            ...
        }

## Describe the solution you'd like
I wonder if it would be possible to make validate also accept references to properties bound to objects, like so:

        validate(this) {
            validate(it::name).isNotNull().isNotBlank()
            validate(it::taxId).isNotNull().isNotBlank()
            validate(it::phone).isNotNull().isNotBlank()
            ...
        }

## Describe alternatives you've considered

I have only dabbled around the source code for valiktor, but I suppose that one solution would be for validate() functions to accept `KProperty0<T?>` as well. I can try to hammer away something on a PR if you think it'd be worth it.

**Comment by rodolphocouto** [comment] 2019-10-27 21:24
Hi @fmobus,

I've been thinking about it, but the problem is that solution isn't type safe. The validation function expects a `KProperty1<E, T?>`, where `E` must be the same object of the validation block.

We can implement a overload function expecting `KProperty0<T?>` as you said, but it would allow validating a different object type from the validation block.

So I'm not sure if that solution is better than writing the class name multiple times.

**Comment by rodolphocouto** [comment] 2020-02-08 18:30
I'm closing this issue by now, let me know if you have any questions.

**Closed by rodolphocouto** 2020-02-08 18:30 UTC
